### ISSUE TITLE
Daily timer/tasks

### ISSUE THREAD

**Issue by adapap** [Musimaniac/IdleonCompanion#9]
Reimplement functionality to have a daily reset on checklists. Many ways to approach this one. One way is a "daily": boolean prop on tasks, such that all tasks with the "daily" prop set to true are reset every day at a fixed time.

Bonus: More metadata to keep track of with tasks, including categories, priority, progress (e.g. percent complete), color, etc.

**Comment by Musimaniac** [comment]
couldn't we use the task.reset value to determine if a task is a daily?

about the bonus part, I'd say to write it up as a low priority addition, It could become really useful as a way for users to custom tag their own task, or as way to add color based on category. we could also build separated lists based on category, so that users with a lot of customs tasks could have a way to more easily track them. 

In general, ecxiting possibilities with this feature
